// src/components/AnalysisView.tsx
import React, { useMemo, useState } from 'react';
import { AnalysisResult, DecisionState } from '../types';
import { Card, CardContent, CardHeader, CardTitle, Button } from './ui';
import {
  Radar,
  RadarChart,
  PolarGrid,
  PolarAngleAxis,
  ResponsiveContainer,
  BarChart,
  Bar,
  XAxis,
  YAxis,
  Tooltip,
  Legend,
  Cell
} from 'recharts';
import { Trophy, ArrowLeft, RotateCcw, CheckCircle2, AlertTriangle, FileText, Download } from 'lucide-react';
import { clsx } from 'clsx';
import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';

interface AnalysisViewProps {
  state: DecisionState;
  onReset: () => void;
  onBack: () => void;
}

export const AnalysisView: React.FC<AnalysisViewProps> = ({ state, onReset, onBack }) => {
  const { result, criteria, options } = state;
  const [isGeneratingPdf, setIsGeneratingPdf] = useState(false);

  if (!result) return null;

  // Prepare chart data
  const chartData = useMemo(() => {
    return criteria.map(c => {
      const dataPoint: any = { subject: c.name, fullMark: 100 };
      result.analysis.forEach(optAnalysis => {
        const score = optAnalysis.criteriaAnalysis.find(ca => ca.criteriaId === c.id)?.score ?? 0;
        const optName = options.find(o => o.id === optAnalysis.optionId)?.name ?? optAnalysis.optionId;
        dataPoint[optName] = score;
      });
      return dataPoint;
    });
  }, [criteria, result.analysis, options]);

  // Calculate weighted totals for display
  const weightedScores = useMemo(() => {
    return result.analysis.map(opt => {
      let totalWeighted = 0;
      let totalPossible = 0;

      opt.criteriaAnalysis.forEach(ca => {
        const crit = criteria.find(c => c.id === ca.criteriaId);
        if (crit) {
          totalWeighted += (ca.score * crit.weight);
          totalPossible += (100 * crit.weight);
        }
      });

      const percentage = totalPossible > 0 ? (totalWeighted / totalPossible) * 100 : 0;
      return {
        ...opt,
        percentage: Math.round(percentage)
      };
    }).sort((a, b) => b.percentage - a.percentage);
  }, [result, criteria]);

  const winnerOption = options.find(o => o.id === result.winnerId);
  const colors = ['#f59e0b', '#3b82f6', '#10b981', '#ec4899', '#8b5cf6'];

  // PDF generation: captures the analysis root and exports to PDF
  const handleDownloadPdf = async () => {
    setIsGeneratingPdf(true);
    try {
      // find the DOM node to capture
      const element = document.getElementById('analysis-root');
      if (!element) {
        throw new Error("Analysis DOM element not found.");
      }

      // adjust scroll/scale for sharpness
      const originalScrollY = window.scrollY;
      window.scrollTo({ top: 0 });

      // capture at higher scale for better quality
      const canvas = await html2canvas(element, {
        useCORS: true,
        scale: 2,
        logging: false,
        backgroundColor: null
      });

      const imgData = canvas.toDataURL('image/png');
      const pdf = new jsPDF({
        orientation: 'portrait',
        unit: 'pt',
        format: 'a4'
      });

      // A4 size in points
      const pageWidth = pdf.internal.pageSize.getWidth();
      const pageHeight = pdf.internal.pageSize.getHeight();

      // scale image to fit page while preserving aspect ratio
      const imgWidth = canvas.width;
      const imgHeight = canvas.height;
      const ratio = Math.min(pageWidth / imgWidth, pageHeight / imgHeight);
      const imgScaledWidth = imgWidth * ratio;
      const imgScaledHeight = imgHeight * ratio;

      const marginX = (pageWidth - imgScaledWidth) / 2;
      const marginY = 20;

      pdf.addImage(imgData, 'PNG', marginX, marginY, imgScaledWidth, imgScaledHeight);

      // optional: add footer with timestamp
      const date = new Date().toLocaleString();
      pdf.setFontSize(9);
      pdf.setTextColor('#6b7280');
      pdf.text(`Generated by Decision Sherlock • ${date}`, 40, pageHeight - 20);

      pdf.save(`decision-sherlock-report-${Date.now()}.pdf`);
      window.scrollTo({ top: originalScrollY });
    } catch (err: any) {
      console.error("PDF generation error:", err);
      alert("Failed to generate PDF. See console for details.");
    } finally {
      setIsGeneratingPdf(false);
    }
  };

  return (
    <div id="analysis-root" className="space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-700 relative">
      {/* Loading overlay when generating PDF */}
      {isGeneratingPdf && (
        <div className="absolute inset-0 z-50 flex items-center justify-center bg-black/60">
          <div className="text-center text-white">
            <div className="loader mb-4"><svg className="animate-spin w-12 h-12 mx-auto" viewBox="0 0 24 24"><circle cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" strokeDasharray="60" strokeLinecap="round" fill="none"/></svg></div>
            <div className="text-lg font-semibold">Sherlock is preparing your report…</div>
            <div className="text-sm text-slate-300 mt-2">This can take a few seconds for long reports.</div>
          </div>
        </div>
      )}

      {/* Header Result */}
      <div className="text-center space-y-4">
        <div className="inline-flex items-center justify-center p-3 bg-amber-500/10 rounded-full mb-4 ring-1 ring-amber-500/50">
          <Trophy className="w-8 h-8 text-amber-500" />
        </div>
        <h2 className="text-3xl md:text-4xl font-bold serif text-slate-100">The Verdict is In</h2>
        <p className="text-lg text-slate-400 max-w-2xl mx-auto">
          Based on your criteria, <span className="text-amber-400 font-semibold">{winnerOption?.name}</span> appears to be the superior choice.
        </p>
      </div>

      {/* Main Verdict Card */}
      <Card className="border-amber-500/30 bg-slate-900/80 backdrop-blur-sm">
        <CardHeader>
          <CardTitle className="flex items-center gap-2"><FileText className="w-5 h-5 text-amber-500" /> Sherlock's Deduction</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="prose prose-invert max-w-none text-slate-300 leading-relaxed italic border-l-4 border-amber-500/50 pl-4 py-1">"{result.verdict}"</div>
          <div className="mt-4 pt-4 border-t border-slate-800">
            <h4 className="text-sm font-semibold text-amber-400 mb-2 uppercase tracking-wider">Recommendation</h4>
            <p className="text-slate-300">{result.recommendation}</p>
          </div>
        </CardContent>
      </Card>

      {/* Comparison Chart */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <Card>
          <CardHeader><CardTitle>Criteria Profile</CardTitle></CardHeader>
          <CardContent className="h-[300px]">
            <ResponsiveContainer width="100%" height="100%">
              <RadarChart cx="50%" cy="50%" outerRadius="80%" data={chartData}>
                <PolarGrid stroke="#334155" />
                <PolarAngleAxis dataKey="subject" tick={{ fill: '#94a3b8', fontSize: 12 }} />
                {options.map((opt, i) => (
                  <Radar key={opt.id} name={opt.name} dataKey={opt.name} stroke={colors[i % colors.length]} fill={colors[i % colors.length]} fillOpacity={0.3} />
                ))}
                <Legend />
                <Tooltip contentStyle={{ backgroundColor: '#1e293b', borderColor: '#334155', color: '#f1f5f9' }} itemStyle={{ color: '#e2e8f0' }} />
              </RadarChart>
            </ResponsiveContainer>
          </CardContent>
        </Card>

        <Card>
          <CardHeader><CardTitle>Weighted Performance</CardTitle></CardHeader>
          <CardContent className="h-[300px]">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={weightedScores} layout="vertical" margin={{ top: 5, right: 30, left: 40, bottom: 5 }}>
                <XAxis type="number" domain={[0, 100]} hide />
                <YAxis type="category" dataKey="optionId" hide />
                <Tooltip
                  cursor={{ fill: 'transparent' }}
                  content={({ active, payload }) => {
                    if (active && payload && payload.length) {
                      const data = payload[0].payload;
                      const opt = options.find(o => o.id === data.optionId);
                      return (
                        <div className="bg-slate-800 border border-slate-700 p-2 rounded text-sm text-slate-200">
                          <p className="font-bold">{opt?.name}</p>
                          <p>Score: {data.percentage}%</p>
                        </div>
                      );
                    }
                    return null;
                  }}
                />
                <Bar dataKey="percentage" radius={[0, 4, 4, 0]} barSize={40}>
                  {weightedScores.map((entry, index) => (
                    <Cell key={`cell-${index}`} fill={entry.optionId === result.winnerId ? '#f59e0b' : '#334155'} />
                  ))}
                </Bar>
              </BarChart>
            </ResponsiveContainer>

            {/* Custom Legend/List for Bar Chart because YAxis is hidden */}
            <div className="flex flex-col gap-2 mt-[-280px] ml-2 absolute pointer-events-none">
              {weightedScores.map((score, i) => {
                const opt = options.find(o => o.id === score.optionId);
                return (
                  <div key={score.optionId} className="h-[40px] flex items-center text-sm font-medium text-slate-200 drop-shadow-md">
                    {opt?.name} ({score.percentage}%)
                  </div>
                );
              })}
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Detailed Analysis */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {result.analysis.map((analysis) => {
          const opt = options.find(o => o.id === analysis.optionId);
          const isWinner = analysis.optionId === result.winnerId;

          return (
            <Card key={analysis.optionId} className={clsx("transition-all", isWinner ? "border-amber-500/50 shadow-lg shadow-amber-900/10" : "border-slate-800")}>
              <CardHeader className="pb-2">
                <div className="flex justify-between items-start">
                  <CardTitle className={clsx("text-lg", isWinner ? "text-amber-400" : "text-slate-300")}>{opt?.name}</CardTitle>
                  {isWinner && <Trophy className="w-5 h-5 text-amber-500" />}
                </div>
              </CardHeader>
              <CardContent className="space-y-4">
                {/* Pros/Cons */}
                <div className="grid grid-cols-2 gap-4 text-sm">
                  <div>
                    <h5 className="font-semibold text-emerald-400 mb-2 flex items-center gap-1"><CheckCircle2 className="w-3 h-3" /> Pros</h5>
                    <ul className="list-disc list-inside space-y-1 text-slate-400">
                      {analysis.pros.slice(0, 3).map((pro, i) => <li key={i}>{pro}</li>)}
                    </ul>
                  </div>
                  <div>
                    <h5 className="font-semibold text-red-400 mb-2 flex items-center gap-1"><AlertTriangle className="w-3 h-3" /> Cons</h5>
                    <ul className="list-disc list-inside space-y-1 text-slate-400">
                      {analysis.cons.slice(0, 3).map((con, i) => <li key={i}>{con}</li>)}
                    </ul>
                  </div>
                </div>

                {/* Criteria Breakdown */}
                <div className="pt-4 border-t border-slate-800 space-y-3">
                  <h5 className="text-xs font-semibold uppercase tracking-wider text-slate-500">Key Criteria Analysis</h5>
                  {analysis.criteriaAnalysis.map(ca => {
                    const crit = criteria.find(c => c.id === ca.criteriaId);
                    if (!crit) return null;
                    return (
                      <div key={ca.criteriaId} className="text-sm">
                        <div className="flex justify-between mb-1">
                          <span className="text-slate-300">{crit.name}</span>
                          <span className={clsx("font-mono", ca.score > 80 ? "text-emerald-400" : ca.score < 50 ? "text-red-400" : "text-amber-400")}>
                            {ca.score}/100
                          </span>
                        </div>
                        <p className="text-slate-500 text-xs">{ca.reasoning}</p>
                      </div>
                    );
                  })}
                </div>
              </CardContent>
            </Card>
          );
        })}
      </div>

      {/* Footer actions */}
      <div className="flex justify-center gap-4 pt-8">
        <Button variant="secondary" onClick={onBack}><ArrowLeft className="w-4 h-4 mr-2" /> Review Data</Button>
        <Button variant="ghost" onClick={onReset} className="text-red-400 hover:text-red-300 hover:bg-red-900/20"><RotateCcw className="w-4 h-4 mr-2" /> Start New Case</Button>

        {/* PDF export */}
        <div className="ml-2">
          <Button onClick={handleDownloadPdf} className="inline-flex items-center gap-2">
            <Download className="w-4 h-4" /> Download PDF
          </Button>
        </div>
      </div>
    </div>
  );
};
